mosip/inji-certify

certify-service/src/main/java/io/mosip/certify/plugin/impl/LoggerAuditService.java
Signed-off-by: Challarao <challarao@beehyv.com>
=> [INJICERT-13] added audit plugin implementation

certify-service/src/main/resources/application-local.properties, certify-service/src/test/resources/application-test.properties, docker-compose/docker-compose-certify/config/certify-default.properties
- earlier the `background_image` object key was wrongly placed at the root, now it's moved under `display` object
=> [INJICERT-41] organize background_image key

docker-compose/docker-compose-certify/config/certify-default.properties, docker-compose/docker-compose-certify/postman-collections/certify with sunbird RC flow.postman_collection.json, docker-compose/docker-compose-certify/postman-collections/certify with sunbird flow.postman_environment.json
Signed-off-by: Challarao <challarao@beehyv.com>
=> [INJICERT-212] change certify default properties

certify-service/Dockerfile
Signed-off-by: Challarao <challarao@beehyv.com>
=> [INJICERT-189] fix hsm install sudo privilages

certify-core/pom.xml, certify-core/src/main/java/io/mosip/certify/core/config/RedisCacheConfig.java, certify-core/src/main/java/io/mosip/certify/core/config/SimpleCacheConfig.java, certify-service/Dockerfile, certify-service/configure_start.sh, certify-service/pom.xml, certify-service/src/main/resources/application-local.properties, docker-compose/docker-compose-certify/docker-compose.yml, pom.xml
Signed-off-by: Challarao <challarao@beehyv.com>
=> [INJICERT-189] update hsm client version and add redis configurations

certify-service/pom.xml, certify-service/src/main/java/io/mosip/certify/CertifyServiceApplication.java, certify-service/src/main/java/io/mosip/certify/config/AppConfig.java, pom.xml
Updated keymanager to latest release candidate 1.3.0-SNAPSHOT.
Added fixes which resolve integration issues with the same
=> [INJICER-322] Updated keymanager to latest release candidate 1.3.0-SNAPSHOT

README.md, docker-compose/docker-compose-certify/config/esignet-default.properties, docker-compose/docker-compose-certify/config/esignet-mock-identity.properties, docker-compose/docker-compose-certify/docker-compose.yml
Co-Authored by: Piyush7034 <piyushshukla2100@gmail.com>
Signed-off-by: Harsh Vardhan <harsh59v@gmail.com>
=> [INJICERT-421] add eSignet 1.4.1 support

docker-compose/docker-compose-certify/config/esignet-default.properties, docker-compose/docker-compose-certify/config/esignet-sunbird-insurance.properties
* eSignet avoid looking for sunbird VCI plugin
=> [INJICERT-421] add eSignet 1.4.1 captcha config

certify-service/src/main/java/io/mosip/certify/services/templating/VelocityTemplatingEngineImpl.java
* NOTE: This assumes that every such object has a custom toString() method.
=> [INJICERT-434] add condition for Object and other non-standard types

deploy/inji-certify/install.sh, helm/inji-certify/values.yaml
Reverts mosip/inji-certify#158
=> Revert "[INJICERT-657] Added some deployment changes"

.github/workflows/push-trigger.yml
Signed-off-by: Hitesh Jain <jainhitesh9998@gmail.com>
=> [DSD-6891] remove sonar report for apitest rig

certify-service-with-plugins/Dockerfile, certify-service-with-plugins/pom.xml, certify-service/Dockerfile, certify-service/configure_start.sh
Removed artifactory  as a dependency
Added certify with inbuilt plugin
=> [INJICERT-661]

certify-service/src/main/java/io/mosip/certify/proof/JwtProofValidator.java
Changes:
fix for did:jwk resolution
made iss as optional, remove exp field
=> [INJICERT-895] Bug fixes relateed to spec compliance

certify-service-with-plugins/Dockerfile, certify-service/src/main/java/io/mosip/certify/proof/JwtProofValidator.java
fixed issue related to concurrency and static variable
=> [INJICERT-895]

db_upgrade_script/mosip_certify/sql/0.10.0_to_0.10.1_rollback.sql, db_upgrade_script/mosip_certify/sql/0.10.0_to_0.10.1_upgrade.sql, db_upgrade_script/mosip_certify/sql/0.10.1_to_0.10.2_rollback.sql, db_upgrade_script/mosip_certify/sql/0.10.1_to_0.10.2_upgrade.sql
[DSD-7420]
[DSD-7420]: https://mosip.atlassian.net/browse/DSD-7420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DSD-7420]

api-test/src/main/resources/testCaseSkippedList.txt
- moving the test cases to known issues for the release
=>  INJICERT-681 - moving the testcases to known issues

docker-compose/docker-compose-injistack/docker-compose.yaml
[INJICERT-961]
[INJICERT-961]: https://mosip.atlassian.net/browse/INJICERT-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJICERT-961] Changed mosipdev img to mosipqa for docker setup

certify-service/src/main/java/io/mosip/certify/filter/AccessTokenValidationFilter.java
Changed aud condition from containsAll to contains to check for one url in audiences
=> [INJCIERT-903] Changed aud condition from containsAll to contains to check for one url in audiences

docker-compose/docker-compose-injistack/README.md
Added use of inji-certify-with-plugins docker image in readme
=> [INJICERT-961] Added use of inji-certify-with-plugins docker image in readme

certify-service/src/main/java/io/mosip/certify/proof/DIDjwkProofManager.java, certify-service/src/main/java/io/mosip/certify/proof/DIDkeysProofManager.java, certify-service/src/main/java/io/mosip/certify/proof/JwtProofKeyManager.java, certify-service/src/main/java/io/mosip/certify/proof/JwtProofValidator.java, certify-service/src/main/java/io/mosip/certify/services/CertifyIssuanceServiceImpl.java, certify-service/src/test/java/io/mosip/certify/proof/DIDjwkProofManagerTest.java, certify-service/src/test/java/io/mosip/certify/proof/DIDkeysProofManagerTest.java, db_scripts/mosip_certify/db.sql
[INJICERT-522] 
- rebase against sd-jwt PR
[INJICERT-522]: https://mosip.atlassian.net/browse/INJICERT-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJICERT-522] add did:key support for parsing ed25519, secpk1

api-test/pom.xml, api-test/src/main/java/io/mosip/testrig/apirig/injicertify/testscripts/DBIntegration.java, api-test/src/main/java/io/mosip/testrig/apirig/injicertify/utils/ExtendedDBManager.java, api-test/src/main/java/io/mosip/testrig/apirig/injicertify/utils/InjiCertifyConstants.java, api-test/src/main/java/io/mosip/testrig/apirig/injicertify/utils/InjiCertifyUtil.java, api-test/src/main/resources/config/injiCertify.properties, api-test/src/main/resources/injicertify/SunBirdC/AuthenticateUserSunBirdC/AuthenticateUserSunBirdC.yml, api-test/src/main/resources/injicertify/SunBirdCForVd11/AuthenticateUserSunBirdCForVd11/AuthenticateUserSunBirdCForVd11.yml, api-test/src/main/resources/injicertify/SunBirdCForVd12/AuthenticateUserSunBirdCForVd12/AuthenticateUserSunBirdCForVd12.yml, api-test/src/main/resources/injicertify/SunBirdCNegative/AuthenticateUserSunBirdCNeg/AuthenticateUserSunBirdCNeg.yml
- Updated the POM version for Commons.
- Added ExtendedDBManager class and implemented query methods.
- Introduced InjicertifyConstants class.
- Updated Sunbird AuthFactorType to be fetched from runtime configuration.
=> MOSIP-41072 | MOSIP-41074 - Release fixes for injicertify testrig

certify-core/src/main/java/io/mosip/certify/core/dto/CredentialConfigurationDTO.java, certify-service/pom.xml, certify-service/src/main/java/io/mosip/certify/entity/CredentialConfig.java, certify-service/src/main/java/io/mosip/certify/services/CredentialConfigurationServiceImpl.java, certify-service/src/main/java/io/mosip/certify/vcformatters/VelocityTemplatingEngineImpl.java, certify-service/src/main/resources/application-local.properties, certify-service/src/test/resources/schema.sql, db_scripts/mosip_certify/combined.sql, db_scripts/mosip_certify/ddl/certify-credential_config.sql, db_scripts/mosip_certify/ddl/combined.sql, db_upgrade_script/mosip_certify/sql/0.11.0_to_0.12.0_rollback.sql, db_upgrade_script/mosip_certify/sql/0.11.0_to_0.12.0_upgrade.sql, docker-compose/docker-compose-injistack/certify_init.sql, docker-compose/docker-compose-injistack/config/certify-default.properties
=> [INJICERT-769] Add unique credential config key  

api-test/pom.xml, api-test/src/main/resources/injicertify/SunBirdCNegative/AuthenticateUserSunBirdCNeg/AuthenticateUserSunBirdCNeg.yml, api-test/src/main/resources/injicertify/SunBirdCNegative/AuthorizationCodeSunBirdCNeg/AuthorizationCodeSunBirdCNeg.yml, api-test/src/main/resources/injicertify/SunBirdCNegative/GenerateTokenSunBirdCNeg/GenerateTokenSunBirdCNeg.yml, api-test/src/main/resources/injicertify/SunBirdCNegative/GetCredentialSunBirdCNeg/GetCredentialSunBirdCNeg.yml, api-test/src/main/resources/injicertify/SunBirdCNegative/OAuthDetailsRequestSunBirdCNeg/OAuthDetailsRequestSunBirdCNeg.yml
- Changed the pom version.
- Added test cases.
- Changed the testcase name properly.
=> INJICERT-1000 - Added testcases and fixes for the failures

api-test/README.md
MOSIP-41258 - Update the readme file in inji certify release-0.11.x branch
=> MOSIP-41258 - Update the readme file in inji certify release-0.11.x branch

api-test/src/main/java/io/mosip/testrig/apirig/injicertify/utils/InjiCertifyUtil.java, api-test/src/main/resources/injicertify/AddIdentity/AddIdentity.yml, api-test/src/main/resources/injicertify/AddIdentityMock/AddIdentity.yml, api-test/src/main/resources/injicertify/CreateVID/CreateVid.yml, api-test/src/main/resources/injicertify/CreateVID/createVid.hbs, api-test/src/main/resources/injicertify/CreateVID/createVidResult.hbs, api-test/src/main/resources/injicertify/SunBirdC/GetCredentialSunBirdC/GetCredentialSunBirdC.yml, api-test/src/main/resources/injicertify/SunBirdCNegative/GetCredentialSunBirdCNeg/GetCredentialSunBirdCNeg.yml, api-test/src/main/resources/injicertify/VCILandRegistry/GetCredentialForLandRegistry/GetCredentialForLandRegistry.yml, api-test/src/main/resources/injicertify/VCILandRegistryNeg/AuthenticateUserForLandRegistry/AuthenticateUserForLandRegistry.yml, api-test/src/main/resources/injicertify/VCILandRegistryNeg/AuthorizationCodeForLandRegistry/AuthorizationCodeForLandRegistry.yml, api-test/src/main/resources/injicertify/VCILandRegistryNeg/GenerateTokenForLandRegistry/GenerateTokenForLandRegistry.yml, api-test/src/main/resources/injicertify/VCILandRegistryNeg/GetCredentialForLandRegistry/GetCredentialForLandRegistry.yml, api-test/src/main/resources/injicertify/VCILandRegistryNeg/OAuthDetailsRequestForLandRegistry/OAuthDetailsRequestForLandRegistry.yml, api-test/src/main/resources/injicertify/VCIMockIDA/GetCredentialForMockIDA/GetCredentialForMockIDA.yml, api-test/src/main/resources/injicertify/VCIMosipID/AuthenticateUserVCI/AuthenticateUserVCI.yml, api-test/src/main/resources/injicertify/VCIMosipID/AuthorizationCodeVCI/AuthorizationCodeVCI.yml, api-test/src/main/resources/injicertify/VCIMosipID/GenerateTokenVCI/GenerateTokenVCI.yml, api-test/src/main/resources/injicertify/VCIMosipID/GetCredentialMosipID/GetCredentialMosipID.yml, api-test/src/main/resources/injicertify/VCIMosipID/OAuthDetailsRequestVCI/OAuthDetailsRequestVCI.yml, api-test/src/main/resources/injicertify/VCIMosipIDNegative/AuthenticateUserVCINeg/AuthenticateUserVCINeg.yml, api-test/src/main/resources/injicertify/VCIMosipIDNegative/AuthorizationCodeVCINeg/AuthorizationCodeVCINeg.yml, api-test/src/main/resources/injicertify/VCIMosipIDNegative/GenerateTokenVCINeg/GenerateTokenVCINeg.yml, api-test/src/main/resources/injicertify/VCIMosipIDNegative/GetCredentialMosipIDNeg/GetCredentialMosipIDNeg.yml, api-test/src/main/resources/injicertify/VCIMosipIDNegative/OAuthDetailsRequestVCINeg/OAuthDetailsRequestVCINeg.yml, api-test/testNgXmlFiles/injicertifyPrerequisiteSuite.xml
- Added new testcases.
- Added new method in util class for EC signature generation.
=> INJICERT-1000 - Added testcases

docker-compose/docker-compose-injistack/README.md
[DSD-7977] release changes
[DSD-7977]: https://mosip.atlassian.net/browse/DSD-7977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DSD-7977] Updated README.md

certify-core/src/main/java/io/mosip/certify/core/dto/CredentialConfigurationDTO.java, certify-core/src/main/java/io/mosip/certify/core/dto/CredentialConfigurationSupportedDTO.java, certify-core/src/main/java/io/mosip/certify/core/dto/CredentialIssuerMetadataDTO.java, certify-core/src/main/java/io/mosip/certify/core/dto/CredentialIssuerMetadataVD11DTO.java, certify-core/src/main/java/io/mosip/certify/core/dto/CredentialIssuerMetadataVD12DTO.java, certify-core/src/main/java/io/mosip/certify/core/dto/CredentialIssuerMetadataVD13DTO.java, certify-core/src/main/java/io/mosip/certify/core/dto/CredentialRequest.java, certify-integration-api/src/main/java/io/mosip/certify/api/dto/VCRequestDto.java, certify-service/src/main/java/io/mosip/certify/entity/CredentialConfig.java, certify-service/src/main/java/io/mosip/certify/repository/CredentialConfigRepository.java, certify-service/src/main/java/io/mosip/certify/services/CertifyIssuanceServiceImpl.java, certify-service/src/main/java/io/mosip/certify/services/CredentialConfigurationServiceImpl.java, certify-service/src/main/java/io/mosip/certify/utils/CredentialUtils.java, certify-service/src/main/java/io/mosip/certify/utils/VCIssuanceUtil.java, certify-service/src/main/java/io/mosip/certify/vcformatters/VelocityTemplatingEngineImpl.java, certify-service/src/test/java/io/mosip/certify/controller/CredentialConfigControllerTest.java, certify-service/src/test/java/io/mosip/certify/services/CertifyIssuanceServiceImplTest.java, certify-service/src/test/java/io/mosip/certify/services/CredentialConfigurationServiceImplTest.java, certify-service/src/test/java/io/mosip/certify/services/VCIssuanceServiceImplTest.java, certify-service/src/test/resources/schema.sql, db_scripts/mosip_certify/combined.sql, db_scripts/mosip_certify/ddl/certify-credential_config.sql, db_scripts/mosip_certify/ddl/combined.sql, db_upgrade_script/mosip_certify/sql/0.11.0_to_0.12.0_rollback.sql, db_upgrade_script/mosip_certify/sql/0.11.0_to_0.12.0_upgrade.sql, docker-compose/docker-compose-injistack/certify_init.sql
=> Add version support for vc type addition and few changes related to sd-jwt.

certify-service/src/main/java/io/mosip/certify/services/CertifyIssuanceServiceImpl.java, certify-service/src/main/java/io/mosip/certify/services/CredentialConfigurationServiceImpl.java, certify-service/src/main/java/io/mosip/certify/utils/VCIssuanceUtil.java, certify-service/src/main/java/io/mosip/certify/validators/SdJwtCredentialRequestValidator.java, certify-service/src/test/java/io/mosip/certify/services/CredentialConfigurationServiceImplTest.java, certify-service/src/test/java/io/mosip/certify/validators/CredentialRequestValidatorTest.java, certify-service/src/test/resources/application-test.properties, docker-compose/docker-compose-injistack/certify_init.sql, docker-compose/docker-compose-injistack/config/certify-csvdp-farmer.properties, docker-compose/docker-compose-injistack/config/certify-default.properties, docker-compose/docker-compose-injistack/docker-compose.yaml
[INJICERT-1025]
[INJICERT-1025]: https://mosip.atlassian.net/browse/INJICERT-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJICERT-1025] Credential endpoint fix for docker-compose well-known

certify-service/src/main/java/io/mosip/certify/services/CredentialConfigurationServiceImpl.java, certify-service/src/test/java/io/mosip/certify/services/CredentialConfigurationServiceImplTest.java
[INJICERT-1029]
[INJICERT-1029]: https://mosip.atlassian.net/browse/INJICERT-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJICERT-1029] Add fix for delete config response

certify-service/src/main/java/io/mosip/certify/proof/DIDkeysProofManager.java
for more details see previous commits with the same Jira ID
=> [INJICERT-1047] avoid sign bit bugs for did:key as well

docs/Presentation-During-Issuance.md
[INJICERT-1034]
Added presentation during issuance flow
[INJICERT-1034]: https://mosip.atlassian.net/browse/INJICERT-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJICERT-1034]

.github/workflows/push-trigger.yml
[INJICERT-1074]
[INJICERT-1074]: https://mosip.atlassian.net/browse/INJICERT-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJICERT-1074] Remove publish to nexus for inji-certify build

certify-service/pom.xml, certify-service/src/main/java/io/mosip/certify/CertifyServiceApplication.java, certify-service/src/main/java/io/mosip/certify/credential/SDJWT.java, certify-service/src/main/java/io/mosip/certify/utils/SDJsonUtils.java, certify-service/src/test/java/io/mosip/certify/credential/SDJWTTest.java, pom.xml
These are the reference PRs which were merged to release branch: #401 and #402
=> [INJICERT-1169] [INJICERT-1060] Move keymanager and sd jwt disclosure fix to develop. 

docs/inji-certify-openapi.yaml
- Added description for fields in API documentation
- Added summary and description for the endpoints
- Added deprecated tag to /system-info/uploadCertificate endpoint
Stoplight link - changes are published for v0.12.0 : [https://mosip.stoplight.io/docs/inji-certify/branches/0.12.0]()
=> [INJICERT-1123] Add missing description for fields in API documentation

README.md
Reference confluence page : https://mosip.atlassian.net/wiki/spaces/~712020a354eedce17e400cb961a8a3f716ad4f/pages/1873444928/Inji+Certify+-+Readme+Structure
=> [INJICERT-1153]  Update ReadMe file for inji-certify repository as per 0.12.0 release changes

api-test/src/main/java/io/mosip/testrig/apirig/injicertify/utils/InjiCertifyUtil.java
Added compatibility of generate Token as per eSignet 1.6.1
=> injicert-1200

certify-core/pom.xml, certify-integration-api/pom.xml, certify-service-with-plugins/pom.xml, certify-service/pom.xml, pom.xml
Upgrade certify version to 0.13.0-SNAPSHOT
Upgrade plugin version to 0.50
=> [INJICERT-1215] Upgrade certify and plugin versions

certify-service/src/main/java/io/mosip/certify/services/CredentialConfigurationServiceImpl.java, certify-service/src/main/java/io/mosip/certify/validators/credentialconfigvalidators/LdpVcCredentialConfigValidator.java, certify-service/src/main/java/io/mosip/certify/validators/credentialconfigvalidators/MsoMdocCredentialConfigValidator.java, certify-service/src/main/java/io/mosip/certify/validators/credentialconfigvalidators/SdJwtCredentialConfigValidator.java, certify-service/src/test/java/io/mosip/certify/services/CredentialConfigurationServiceImplTest.java, certify-service/src/test/java/io/mosip/certify/validators/credentialconfigvalidators/LdpVcCredentialConfigValidatorTest.java, certify-service/src/test/java/io/mosip/certify/validators/credentialconfigvalidators/MsoMdocCredentialConfigValidatorTest.java, certify-service/src/test/java/io/mosip/certify/validators/credentialconfigvalidators/SdJwtCredentialConfigValidatorTest.java
Refactor credential configuration service to convert to entity only after validation passes.
=> [INJICERT-1193] Refactor credential configuration service to convert to entity only after validation passes
